name: NetherCubeParkour
main: com.gmail.justbru00.nethercube.parkour.main.NetherCubeParkour
version: 1.6-RC6
authors: [JustBru00,Justin Brubaker,SethTheLasersloth]
softdepend: [HolographicDisplays]
api-version: 1.16
commands:
  courses:
    description: Command for opening gui.
    aliases: [c]
  parkouradmin:
    description: The command for admin/test features.
    aliases: [prkadmin]
  parkourbalance:
    description: Command to view your current elytra currency balance.
    aliases: [prkbal]   
  parkourlobby:
    description: Command to teleport to the elytra lobby and leave the current map.
    aliases: [prklobby] 
  parkourtp:
    description: Teleports a player to the specified map. It won't work if they don't own the map.
    aliases: [prktp]
  parkourstart:
    description: Starts the given course for the given player.
  parkourstop:
    description: Ends the given course for the given player.    
  boatkill:
    description: Kills all boats that do not have players riding in them.  
  parkourcheckpoint:
    description: Activates mandatory hidden checkpoint for the given player.  
  toptimes:
    description: Allows the user to list the top times for a course.  