name: EpicIceTrack
main: com.justbru00.epic.icetrack.main.EpicIceTrack
version: 2.0-RC2
authors: [JustBru00,Justin Brubaker,SethTheLasersloth]
softdepend: [HolographicDisplays, Multiverse-Core]
api-version: 1.16
commands:
  courses:
    description: Command for opening gui.
    aliases: [c]
  trackadmin:
    description: The command for admin/test features.
    aliases: [prkadmin, parkouradmin, tadmin] 
  trackstart:
    description: Starts the given course for the given player.
    aliases: [parkourstart]
  trackstop:
    description: Ends the given course for the given player.    
    aliases: [parkourstop]
  boatkill:
    description: Kills all boats that do not have players riding in them.  
  trackcheckpoint:
    description: Activates mandatory hidden checkpoint for the given player.  
    aliases: [parkourcheckpoint]
  toptimes:
    description: Allows the user to list the top times for a course.  